name: Publish
on:
  # manual trigger
  workflow_dispatch:
  # on release creation
  release:
    types: [created, edited]
  # on tag creation
  push:
    tags:
      - '*-alpha.*'
      - '*-beta.*'
      - '*-rc.*'
jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml
  publish:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.yarnpkg.com/

      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build package
        run: yarn build

      - name: Publish package on release (run only on release creation and it's master branch)
        if: ${{ success() && github.event_name == 'release' && github.event.release.draft == false }}
        run: |
          if [[ ${{ github.event.release.prerelease }} == true ]]; then
          echo "next\n";
            yarn publish --tag next;
          else
            echo "prod\n";
            yarn publish;
          fi

      - name: Publish package on tag (run only on tag)
        if: ${{ success() && github.event_name == 'push' && github.ref_type == 'tag' }}
        run: |
          if [[ ${{ github.ref }} =~ .*-alpha.* ]]; then
            echo "next\n";
            yarn publish --tag next;
          else
            echo "prod\n";
            yarn publish;
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}