name: Publish
on:
  # on release
  release:
    types: [created]
  
jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml
  publish:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.yarnpkg.com/

      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build package
        run: yarn build

      - name: Publish package
        if: github.event_name == 'release' && github.event.release.draft == false
        run: |
          # run yarn publish --tag next if the release is a prerelease or tag is includes alpha, beta, rc
          if [[ ${{ github.event.release.prerelease }} == true || ${{ github.event.release.tag_name }} =~ -alpha|-beta|-rc ]]; then
            echo "branch: ${{ github.ref }}"
            yarn publish --tag next
          else
            echo "branch: ${{ github.ref }}"
            yarn publish
          fi

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}