name: Publish
on:
  # manual trigger
  workflow_dispatch:
  # on release creation
  release:
    types: [created, edited]
  # on tag creation (v3.0.0-alpha.0)
  push:
    tags:
      - '*-alpha.*'
      - '*-beta.*'
      - '*-rc.*'
jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml
  publish:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.yarnpkg.com/

      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build package
        run: yarn build

      - name: Publish package
        if: ${{ success() && github.event.release.draft == false }}
        run: |
          if [ ${{github.event.release.prerelease}} == true || (${{github.ref}} =~ '-alpha|-beta|-rc') ];
            yarn publish --tag next;
          else
            yarn publish;
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
