name: Publish
on:
  # manual trigger
  workflow_dispatch:
  # on tag creation
  push:
    tags:
      - '*-alpha.*'
      - '*-beta.*'
      - '*-rc.*'
      - 'v*.*.*'
jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml
  publish:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.yarnpkg.com/

      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build package
        run: yarn build

      - name: Publish package
        run: |
          if [[ (${{ github.ref_type }} == 'tag' && ${{ github.ref }} =~ -alpha|-beta|-rc) || (${{ github.ref_type }} == 'branch' && ${{ github.ref }} != 'master') ]]; then
            echo "next\n reference: ${{ github.ref }}";
            yarn publish --tag next;
          else
            echo "prod\n reference: ${{ github.ref }}";
            yarn publish --tag latest;
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}